In [ ]:
#Лабораторна робота №4 Масалітін Ілля Вадимович ФІТ 4-8

In [10]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

data = load_breast_cancer()
X = data.data
y = data.target

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)


log_reg = LogisticRegression(max_iter=20000)
log_reg_params = {'C': [0.01, 0.1, 1, 10, 100]}
log_reg_gs = GridSearchCV(log_reg, log_reg_params, cv=5, scoring='accuracy')
log_reg_gs.fit(X_train_scaled, y_train)

tree_clf = DecisionTreeClassifier()
tree_params = {'max_depth': [None, 10, 20, 30, 40, 50]}
tree_gs = GridSearchCV(tree_clf, tree_params, cv=5, scoring='accuracy')
tree_gs.fit(X_train, y_train)

forest_clf = RandomForestClassifier()
forest_params = {'n_estimators': [50, 100, 200], 'max_depth': [None, 10, 20, 30]}
forest_gs = GridSearchCV(forest_clf, forest_params, cv=5, scoring='accuracy')
forest_gs.fit(X_train, y_train)

def evaluate_model(model, X_test, y_test):
    y_pred = model.predict(X_test)
    accuracy = accuracy_score(y_test, y_pred)
    conf_matrix = confusion_matrix(y_test, y_pred)
    class_report = classification_report(y_test, y_pred)
    return accuracy, conf_matrix, class_report

print("\nОцінка Логістичної регресії:")
log_reg_accuracy, log_reg_conf_matrix, log_reg_class_report = evaluate_model(log_reg_gs.best_estimator_, X_test_scaled, y_test)
print("Точність:", log_reg_accuracy)
print("Матриця помилок:\n", log_reg_conf_matrix)
print("Звіт про класифікацію:\n", log_reg_class_report)

print("\nОцінка Дерева рішень:")
tree_accuracy, tree_conf_matrix, tree_class_report = evaluate_model(tree_gs.best_estimator_, X_test, y_test)
print("Точність:", tree_accuracy)
print("Матриця помилок:\n", tree_conf_matrix)
print("Звіт про класифікацію:\n", tree_class_report)

print("\nОцінка Випадкового лісу:")
forest_accuracy, forest_conf_matrix, forest_class_report = evaluate_model(forest_gs.best_estimator_, X_test, y_test)
print("Точність:", forest_accuracy)
print("Матриця помилок:\n", forest_conf_matrix)
print("Звіт про класифікацію:\n", forest_class_report)

best_model = max([(log_reg_gs.best_estimator_, log_reg_accuracy), 
                   (tree_gs.best_estimator_, tree_accuracy), 
                   (forest_gs.best_estimator_, forest_accuracy)], key=lambda x: x[1])[0]

print("\nНайкраща модель:")
print(best_model)

y_pred = best_model.predict(X_test)
print("\nРезультати прогнозування:")
print(y_pred)



Оцінка Логістичної регресії:
Точність: 0.9824561403508771
Матриця помилок:
 [[ 62   1]
 [  2 106]]
Звіт про класифікацію:
               precision    recall  f1-score   support

           0       0.97      0.98      0.98        63
           1       0.99      0.98      0.99       108

    accuracy                           0.98       171
   macro avg       0.98      0.98      0.98       171
weighted avg       0.98      0.98      0.98       171


Оцінка Дерева рішень:
Точність: 0.9298245614035088
Матриця помилок:
 [[60  3]
 [ 9 99]]
Звіт про класифікацію:
               precision    recall  f1-score   support

           0       0.87      0.95      0.91        63
           1       0.97      0.92      0.94       108

    accuracy                           0.93       171
   macro avg       0.92      0.93      0.93       171
weighted avg       0.93      0.93      0.93       171


Оцінка Випадкового лісу:
Точність: 0.9649122807017544
Матриця помилок:
 [[ 59   4]
 [  2 106]]
Звіт про клас

In [ ]:
#№2

In [13]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

df = pd.read_csv('D:\\titanic (2).csv', delimiter=',', header=0)

df = df[['Survived', 'Pclass', 'Sex', 'Age', 'Fare']]
df['Sex'] = df['Sex'].map({'male': 0, 'female': 1})
df.dropna(inplace=True) 

X = df[['Pclass', 'Sex', 'Age', 'Fare']]
y = df['Survived']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)


log_reg = LogisticRegression(max_iter=20000)
log_reg_params = {'C': [0.01, 0.1, 1, 10, 100]}
log_reg_gs = GridSearchCV(log_reg, log_reg_params, cv=5, scoring='accuracy')
log_reg_gs.fit(X_train_scaled, y_train)

tree_clf = DecisionTreeClassifier()
tree_params = {'max_depth': [None, 10, 20, 30, 40, 50]}
tree_gs = GridSearchCV(tree_clf, tree_params, cv=5, scoring='accuracy')
tree_gs.fit(X_train, y_train)

forest_clf = RandomForestClassifier()
forest_params = {'n_estimators': [50, 100, 200], 'max_depth': [None, 10, 20, 30]}
forest_gs = GridSearchCV(forest_clf, forest_params, cv=5, scoring='accuracy')
forest_gs.fit(X_train, y_train)

def evaluate_model(model, X_test, y_test):
    y_pred = model.predict(X_test)
    accuracy = accuracy_score(y_test, y_pred)
    conf_matrix = confusion_matrix(y_test, y_pred)
    class_report = classification_report(y_test, y_pred)
    return accuracy, conf_matrix, class_report

log_reg_accuracy, log_reg_conf_matrix, log_reg_class_report = evaluate_model(log_reg_gs.best_estimator_, X_test_scaled, y_test)
print("\nОцінка Логістичної регресії:")
print("Точність:", log_reg_accuracy)
print("Матриця помилок:\n", log_reg_conf_matrix)
print("Звіт про класифікацію:\n", log_reg_class_report)

tree_accuracy, tree_conf_matrix, tree_class_report = evaluate_model(tree_gs.best_estimator_, X_test, y_test)
print("\nОцінка Дерева рішень:")
print("Точність:", tree_accuracy)
print("Матриця помилок:\n", tree_conf_matrix)
print("Звіт про класифікацію:\n", tree_class_report)

forest_accuracy, forest_conf_matrix, forest_class_report = evaluate_model(forest_gs.best_estimator_, X_test, y_test)
print("\nОцінка Випадкового лісу:")
print("Точність:", forest_accuracy)
print("Матриця помилок:\n", forest_conf_matrix)
print("Звіт про класифікацію:\n", forest_class_report)

best_model = max([(log_reg_gs.best_estimator_, log_reg_accuracy), 
                   (tree_gs.best_estimator_, tree_accuracy), 
                   (forest_gs.best_estimator_, forest_accuracy)], key=lambda x: x[1])[0]

print("\nНайкраща модель:")
print(best_model)

sample_data = X_test.head(10).values
sample_predictions = best_model.predict(sample_data)
print("\nПрогнозування для 10 випадків:")
print(sample_predictions)



Оцінка Логістичної регресії:
Точність: 1.0
Матриця помилок:
 [[66  0]
 [ 0 34]]
Звіт про класифікацію:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        66
           1       1.00      1.00      1.00        34

    accuracy                           1.00       100
   macro avg       1.00      1.00      1.00       100
weighted avg       1.00      1.00      1.00       100


Оцінка Дерева рішень:
Точність: 1.0
Матриця помилок:
 [[66  0]
 [ 0 34]]
Звіт про класифікацію:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        66
           1       1.00      1.00      1.00        34

    accuracy                           1.00       100
   macro avg       1.00      1.00      1.00       100
weighted avg       1.00      1.00      1.00       100


Оцінка Випадкового лісу:
Точність: 1.0
Матриця помилок:
 [[66  0]
 [ 0 34]]
Звіт про класифікацію:
               precision    recall  f1-scor