In [24]:
#Лабораторна робта № 1 Варіант № 22 Масалітін Ілля Вадимович, ФІТ 4-8

In [25]:
#1 Створіть одновимірний масив (вектор) зі значеннями 𝑒^𝑥 для кожного натурального числа x, починаючи з 1, та виведіть його значення.
import numpy as np
a = np.arange(1, 11)
e_x = np.exp(a)
print(e_x)

[2.71828183e+00 7.38905610e+00 2.00855369e+01 5.45981500e+01
 1.48413159e+02 4.03428793e+02 1.09663316e+03 2.98095799e+03
 8.10308393e+03 2.20264658e+04]


In [26]:
#2 Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його тангенсами кожного натурального числа, починаючи з 1, та виведіть його значення.
import numpy as np
a = np.arange(1, 10)
tan_a = np.tan(a)

tan_matrix = tan_a.reshape(3, 3)

print(tan_matrix)

[[ 1.55740772 -2.18503986 -0.14254654]
 [ 1.15782128 -3.38051501 -0.29100619]
 [ 0.87144798 -6.79971146 -0.45231566]]


In [27]:
#3 Створіть масив розміром 3x3, заповніть його випадковими дійсними числами від -1 до 1 та виведіть непарні числа.
import numpy as np

array = np.random.uniform(-1, 1, (3, 3))
print("Масив 3x3:")
print(array)

print("Числа, які не є кратними 2:")
for row in array:
    for value in row:
        if value % 2 != 0:
            print(value)

Масив 3x3:
[[-0.23404362  0.56897629 -0.51501647]
 [-0.19290498  0.8346955   0.77100327]
 [ 0.06997221  0.94628844 -0.95557233]]
Числа, які не є кратними 2:
-0.2340436170556428
0.5689762861846273
-0.5150164726938571
-0.19290497535385964
0.8346954955389878
0.7710032698474094
0.0699722145982713
0.9462884437127146
-0.9555723313799136


In [28]:
#4 Створіть масив розміром 4x4, заповніть його випадковими дійсними числами від -0.8 до 0.8 та виведіть його значення.
import numpy as np
array = np.random.uniform(-0.8, 0.8, (4, 4))

print("Масив 4x4:")
print(array)

Масив 4x4:
[[-0.53405092  0.25935911 -0.28686854 -0.04875631]
 [-0.28734895  0.65547508  0.55994529  0.03902989]
 [-0.71239153  0.43451891 -0.3349505   0.67808982]
 [-0.37172287  0.76406474 -0.56797912 -0.41761437]]


In [29]:
#5 Створіть два одновимірних масиви розміром 6, заповніть їх випадковими цілими числами в діапазоні від 5 до 15 та виконайте на них поелементні операції додавання, віднімання та множення.
import numpy as np

array1 = np.random.randint(5, 16, 6)
array2 = np.random.randint(5, 16, 6)


print("Масив 1:")
print(array1)

print("Масив 2:")
print(array2)


addition = array1 + array2
subtraction = array1 - array2
multiplication = array1 * array2


print("Додавання:")
print(addition)

print("Віднімання:")
print(subtraction)

print("Множення:")
print(multiplication)

Масив 1:
[12  8  7 12 13 13]
Масив 2:
[14  9  9  6  5 12]
Додавання:
[26 17 16 18 18 25]
Віднімання:
[-2 -1 -2  6  8  1]
Множення:
[168  72  63  72  65 156]


In [30]:
#6 Створіть дві матриці 4x4, заповніть їх довільними цілими числами від -6 до 6 та знайдіть їх добуток.
import numpy as np

matrix1 = np.random.randint(-6, 7, (4, 4))
matrix2 = np.random.randint(-6, 7, (4, 4))


print("Матриця 1:")
print(matrix1)

print("Матриця 2:")
print(matrix2)



product = np.dot(matrix1, matrix2)


print("Добуток матриць:")
print(product)

Матриця 1:
[[ 0  5  2 -6]
 [ 5 -3 -2 -5]
 [-4 -1 -4  6]
 [ 0 -1  0 -1]]
Матриця 2:
[[ 6  0 -3  6]
 [-4 -1 -1  3]
 [ 3 -2 -2  5]
 [ 3  6  4 -6]]
Добуток матриць:
[[-32 -45 -33  61]
 [ 21 -23 -28  41]
 [-14  45  45 -83]
 [  1  -5  -3   3]]


In [31]:
#7 Створіть дві матриці розміром 3x2 та 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 8 та перемножте їх між собою.
import numpy as np

matrix1 = np.random.randint(1, 9, (3, 2))
matrix2 = np.random.randint(1, 9, (2, 2))


print("Матриця 3x2:")
print(matrix1)

print("Матриця 2x2:")
print(matrix2)


product = np.dot(matrix1, matrix2)


print("Добуток матриць:")
print(product)

Матриця 3x2:
[[7 4]
 [7 7]
 [8 5]]
Матриця 2x2:
[[6 4]
 [6 1]]
Добуток матриць:
[[66 32]
 [84 35]
 [78 37]]


In [32]:
#8 Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 8 та знайдіть її обернену матрицю.
import numpy as np


matrix = np.random.randint(1, 9, (3, 3))

print("Матриця 3x3:")
print(matrix)


if np.linalg.det(matrix) != 0:
    inverse_matrix = np.linalg.inv(matrix)
    print("Обернена матриця:")
    print(inverse_matrix)
else:
    print("Матриця є виродженою і не має оберненої матриці.")

Матриця 3x3:
[[3 3 7]
 [5 7 5]
 [2 3 6]]
Обернена матриця:
[[ 0.96428571  0.10714286 -1.21428571]
 [-0.71428571  0.14285714  0.71428571]
 [ 0.03571429 -0.10714286  0.21428571]]


In [33]:
#9 Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від -1 до 1 та транспонуйте її.
import numpy as np

matrix = np.random.uniform(-1, 1, (4, 4))


print("Матриця 4x4:")
print(matrix)


transposed_matrix = np.transpose(matrix)


print("Транспонована матриця:")
print(transposed_matrix)

Матриця 4x4:
[[ 0.15314794 -0.90459625  0.84533466  0.00177714]
 [-0.42701418  0.08289304 -0.23573802  0.22766583]
 [-0.68780639 -0.98045721  0.25705907 -0.52506337]
 [-0.4161957  -0.5547201   0.2065331  -0.95211199]]
Транспонована матриця:
[[ 0.15314794 -0.42701418 -0.68780639 -0.4161957 ]
 [-0.90459625  0.08289304 -0.98045721 -0.5547201 ]
 [ 0.84533466 -0.23573802  0.25705907  0.2065331 ]
 [ 0.00177714  0.22766583 -0.52506337 -0.95211199]]


In [34]:
#10 Створіть матрицю розміром 3x4 та вектор розміром 4x1, заповніть матрицю випадковими дійсними числами від 0 до 1, а вектор - випадковими цілими числами в діапазоні від 1 до 10, і знайдіть добуток матриці на вектор.
import numpy as np

matrix = np.random.uniform(0, 1, (3, 4))
vector = np.random.randint(1, 11, (4, 1))


print("Матриця 3x4:")
print(matrix)

print("Вектор 4x1:")
print(vector)



product = np.dot(matrix, vector)


print("Добуток матриці на вектор:")
print(product)

Матриця 3x4:
[[0.16387457 0.28411656 0.38314614 0.92850822]
 [0.39969211 0.55990615 0.57455865 0.89850145]
 [0.85654818 0.58735121 0.5950211  0.27798746]]
Вектор 4x1:
[[ 5]
 [ 8]
 [10]
 [ 2]]
Добуток матриці на вектор:
[[ 8.78078319]
 [14.02029916]
 [15.48773645]]


In [35]:
#11 Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть матрицю випадковими цілими числами в діапазоні від 1 до 10, а вектор - випадковими дійсними числами від 0 до 1, і знайдіть добуток матриці на вектор.
import numpy as np

matrix = np.random.randint(1, 11, (2, 3))
vector = np.random.uniform(0, 1, 3)


print("Матриця 2x3:")
print(matrix)

print("Вектор з 3 елементів:")
print(vector)


vector_col = vector.reshape(-1, 1)
product = np.dot(matrix, vector)


print("Добуток матриці на вектор:")
print(product)

Матриця 2x3:
[[7 8 5]
 [3 9 4]]
Вектор з 3 елементів:
[0.48202313 0.54047881 0.85838638]
Добуток матриці на вектор:
[11.98992432  9.74392421]


In [36]:
#12 Створіть дві матриці розміром 3x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 3 та знайдіть суму всіх елементів другої матриці.
import numpy as np

matrix1 = np.random.randint(1, 4, (3, 3))
matrix2 = np.random.randint(1, 4, (3, 3))


print("Матриця 1:")
print(matrix1)

print("Матриця 2:")
print(matrix2)



sum_matrix2 = np.sum(matrix2)


print("Сума всіх елементів другої матриці:")
print(sum_matrix2)

Матриця 1:
[[1 2 3]
 [2 1 1]
 [2 1 1]]
Матриця 2:
[[2 2 3]
 [3 3 2]
 [1 1 1]]
Сума всіх елементів другої матриці:
18


In [37]:
#13 Створіть дві матриці розміром 3x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 5 та знайдіть суму їх елементів.
import numpy as np

matrix1 = np.random.randint(1, 6, (3, 3))
matrix2 = np.random.randint(1, 6, (3, 3))


print("Матриця 1:")
print(matrix1)

print("Матриця 2:")
print(matrix2)


sum_matrix1 = np.sum(matrix1)
sum_matrix2 = np.sum(matrix2)


total_sum = sum_matrix1 + sum_matrix2


print("Сума всіх елементів матриці 1:")
print(sum_matrix1)

print("Сума всіх елементів матриці 2:")
print(sum_matrix2)

print("Загальна сума всіх елементів обох матриць:")
print(total_sum)

Матриця 1:
[[1 1 3]
 [1 3 3]
 [4 1 2]]
Матриця 2:
[[1 1 5]
 [1 4 2]
 [2 5 4]]
Сума всіх елементів матриці 1:
19
Сума всіх елементів матриці 2:
25
Загальна сума всіх елементів обох матриць:
44


In [38]:
#14 Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть суму елементів на головній діагоналі.
import numpy as np

matrix = np.random.randint(1, 11, (3, 3))


print("Матриця 3x3:")
print(matrix)


diagonal_sum = np.trace(matrix)


print("Сума елементів на головній діагоналі:")
print(diagonal_sum)

Матриця 3x3:
[[ 4  8  7]
 [ 6  3  4]
 [ 3  5 10]]
Сума елементів на головній діагоналі:
17


In [39]:
#15 Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від -1 до 1 та знайдіть вектор-стовпчик, що містить добуток елементів кожного стовпця матриці.
import numpy as np

matrix = np.random.uniform(-1, 1, (3, 3))


print("Матриця 3x3:")
print(matrix)


column_products = np.prod(matrix, axis=0)

column_products_column_vector = column_products.reshape(-1, 1)


print("Вектор-стовпчик з добутком елементів кожного стовпця:")
print(column_products_column_vector)

Матриця 3x3:
[[-0.50870369 -0.23982927  0.39198057]
 [ 0.14302541 -0.53664448 -0.80274295]
 [ 0.35506284  0.16125956  0.64358138]]
Вектор-стовпчик з добутком елементів кожного стовпця:
[[-0.0258335 ]
 [ 0.0207546 ]
 [-0.20250909]]


In [ ]:
#Висновок: Виконуючи цю лабораторну роботу, я ознайомився з бібліотекою NumPy, а також навчився використовувати меотди даної бібліотеки. 